version: "2"
services:
  db:
    image: "postgres:9.6"
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fofola
    ports:
      - "5432:5432"

  fcrepo:
    image: moravianlibrary/fcrepo:3.8.1
    container_name: fedora
    environment:
      - FEDORA_PASSWORD=fedoraAdmin
      - "FEDORA_DB_JDBC_URL=jdbc:postgresql://fedoraPostgres:5432/fedora3"
      - FEDORA_DB_USER=fedoraAdmin
      - FEDORA_DB_PASSWORD=fedoraAdmin
      - "RITRIPLES_DB_JDBC_URL=jdbc:postgresql://riTriplesPostgres:5432/riTriples"
      - RITRIPLES_DB_USER=fedoraAdmin
      - RITRIPLES_DB_PASSWORD=fedoraAdmin
    ports:
      - "8080:8080"

  fedoraPostgres:
    image: "postgres:9.6"
    container_name: fedora_postgres
    environment:
      - POSTGRES_USER=fedoraAdmin
      - POSTGRES_PASSWORD=fedoraAdmin
      - POSTGRES_DB=fedora3

  riTriplesPostgres:
    image: "postgres:9.6"
    container_name: ritriples
    environment:
      - POSTGRES_USER=fedoraAdmin
      - POSTGRES_PASSWORD=fedoraAdmin
      - POSTGRES_DB=riTriples