version: "2"
services:
  db:
    image: "postgres:11.5"
    container_name: fofola-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fofola
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "log_statement=all"