debug: false
trace: false

server:
  shutdown: graceful
  port: ${PORT:8082}
  error:
    path: /error
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  h2:
    console.enabled: true
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  lifecycle:
    timeout-per-shutdown-phase: 10s

management:
  endpoints:
    web:
      base-path: /api/management
      exposure:
        include: info, startup
      cors:
        allowed-methods: OPTIONS, GET
        allowed-origins: '*'
  info:
    build:
      enabled: true
    env:
      enabled: false
    git:
      enabled: true
  health:
    solr:
      enabled: false

logging:
  level:
    '*': ''
    com:
      zaxxer:
        hikari: ${HIKARI_LOGGING_LVL:WARN}
    org:
      h2: ${H2_LOGGING_LVL:WARN}
      hibernate: ${HIBERNATE_LOGGING_LVL:WARN}
      springframework:
        web:
          client:
            RestTemplate: WARN
