package cz.mzk.fofola.constants.dnnt;

public enum Status {
    NOT_READY,
    ACTIVE,
    PAUSED,
    FINISHED,
    CANT_PREPARE,
    FINISHED_WITH_NEGLIGIBLE_ISSUES,
    FINISHED_WITH_SERIOUS_ISSUES,
    TERMINATED_BY_EXCEPTION,
    TERMINATED_BY_SHUTDOWN,
}
